### ISSUE TITLE
Width settings not working in certain situations

### ISSUE THREAD

**Issue by alairock** [crissNb/FluidNoti#3]
**Describe the bug**
I have the 14-inch, Nov 2023 Macbook Pro M3

<img width="666" alt="image" src="https://github.com/crissNb/FluidNoti/assets/1480236/8be1f171-b9ba-4ee2-85f4-6e0ef4fd4947">

![image](https://github.com/crissNb/FluidNoti/assets/1480236/6ef7086f-f92c-4c0d-a933-07ae91c7d100)

I have added the red outline to show where my notch is and what it covers (approximately)

The height setting seems to work, usually, but the width does not seem to change or be affecting the app.

**Comment by crissNb** [comment]
Hi, thank you for reporting the issue. I will be implementing this change tomorrow. Either you will be able to adjust the display size individually or the app will calculate on its own.

**Comment by crissNb** [comment]
Fixed with 1.0.41.
