### ISSUE TITLE
BUG | Text gets cut off by physical Notch on 15" MBA M2

### ISSUE THREAD

**Issue by SmartGecko44** [crissNb/FluidNoti#5]
**Describe the bug**
Even though the app has the correct measurements of my notch, it cuts off text on specific scenarios like [when hovering over the current song](https://github.com/crissNb/FluidNoti/assets/74975165/0cd60789-67fc-4c7b-b87f-d961c06aea7d) or [when enabling the power saving mode](https://github.com/crissNb/FluidNoti/assets/74975165/1ce3a07f-0813-4c07-b2f8-bae165592495). 

**To Reproduce**
1. Install FluidNoti on a 15" MacBook Air M2
2. Set the dimensions of the notch
3. Play a song and hover over it / enable power saving
4. See the text being blocked

**Expected behavior**
The popup does not get cut off by the physical notch.

**Desktop (please complete the following information):**
 - macOS version: 14.5
 - Architecture: Apple Silicon

**Comment by crissNb** [comment]
Hi, I'll be making the height adjustable as well. The width of the popup notch can be adjusted in settings by changing width under the features settings.

**Comment by crissNb** [comment]
Height adjustment is now included with FluidNoti v1.0.43.
